version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./app:/app
    expose:
      - 5000
    

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80
    depends_on:
      - flask
